# Generated by Django 4.2.29 on 2026-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('title', models.CharField(max_length=120)),
                ('metric', models.CharField(blank=True, help_text='Optional standout number, for example 12 launches.', max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('period', models.CharField(help_text='For example: 2023 - Present', max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField()),
                ('highlights', models.TextField(blank=True, help_text='Optional bullet-style notes. Put each note on a new line.')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated stack, for example Django, PostgreSQL, Figma.', max_length=180)),
                ('result', models.CharField(blank=True, help_text="Optional short outcome like 'Launched in 3 weeks'.", max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('welcome_text', models.CharField(default='Welcome to', max_length=80)),
                ('resume_title', models.CharField(default='My Resume!', max_length=120)),
                ('intro_badge', models.CharField(default='Designer / Developer / Problem Solver', help_text='Short line above the heading.', max_length=120)),
                ('full_name', models.CharField(default='Your Name', max_length=120)),
                ('job_title', models.CharField(default='Creative Developer and Designer', max_length=140)),
                ('availability_note', models.CharField(default='Open to freelance projects and product teams.', max_length=140)),
                ('hero_summary', models.TextField(default='I build clean digital experiences, thoughtful interfaces, and portfolio-ready products with a strong visual voice.')),
                ('about_title', models.CharField(default='About Me', max_length=80)),
                ('about_text', models.TextField(default='Use this area to describe who you are, what you enjoy building, and what makes your approach memorable.')),
                ('skills_title', models.CharField(default='Core Skills', max_length=80)),
                ('experience_title', models.CharField(default='Experience', max_length=80)),
                ('projects_title', models.CharField(default='Portfolio Highlights', max_length=80)),
                ('achievements_title', models.CharField(default='Achievements', max_length=80)),
                ('contact_title', models.CharField(default='Get In Touch', max_length=80)),
                ('contact_note', models.CharField(default='Share your email, phone, and city so people know how to reach you.', max_length=180)),
                ('primary_button_text', models.CharField(default='Contact Me', max_length=40)),
                ('download_button_text', models.CharField(default='Download CV', max_length=40)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, upload_to='cv/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Resume profile',
                'verbose_name_plural': 'Resume profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160)),
                ('icon_label', models.CharField(default='DEV', help_text='Short label inside the icon circle, for example DEV or UI.', max_length=6)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('handle', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
