# Generated by Django 4.2.29 on 2026-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_translate_content_and_remove_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofile',
            name='about_text',
            field=models.TextField(default='В этом блоке можно рассказать о себе, своем опыте, интересах и о том, что делает твой подход особенным.'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='about_title',
            field=models.CharField(default='Обо мне', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='achievements_title',
            field=models.CharField(default='Достижения', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='availability_note',
            field=models.CharField(default='Открыт к проектам, стажировкам и предложениям о сотрудничестве.', max_length=140),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='contact_note',
            field=models.CharField(default='Укажи свои контакты, чтобы с тобой было легко связаться.', max_length=180),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='contact_title',
            field=models.CharField(default='Связаться со мной', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='download_button_text',
            field=models.CharField(default='Скачать CV', max_length=40),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='experience_title',
            field=models.CharField(default='Опыт', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='full_name',
            field=models.CharField(default='Твое имя', max_length=120),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='hero_summary',
            field=models.TextField(default='Создаю аккуратные цифровые продукты, понятные интерфейсы и проекты, которые не стыдно показать в портфолио.'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='intro_badge',
            field=models.CharField(default='Дизайн / Разработка / Продуктовый подход', help_text='Короткая строка над главным заголовком.', max_length=120),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='job_title',
            field=models.CharField(default='Разработчик и дизайнер', max_length=140),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='primary_button_text',
            field=models.CharField(default='Написать мне', max_length=40),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='projects_title',
            field=models.CharField(default='Проекты', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='resume_title',
            field=models.CharField(default='Мое резюме', max_length=120),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='skills_title',
            field=models.CharField(default='Ключевые навыки', max_length=80),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='welcome_text',
            field=models.CharField(default='Добро пожаловать', max_length=80),
        ),
    ]
